### ISSUE TITLE
Bug on Cardfield default text color style and Samsung S24 with Android 14

### ISSUE THREAD

**Issue by almighty972** [stripe/stripe-react-native#1743]
**Describe the bug**
When using the `CardField` component, the default cardStyle text color is white on Samsung Galaxy S24 (Android 14)
On an emulator with Android 8, the `CardField` text color is white only when you select the desired  network (see attached videos)
 

**To Reproduce**
1. Install Stripe sdk "@stripe/stripe-react-native": "0.38.6"
2. Add `<CardField/>` to your screen
3. Launch the application on a Samsung Galaxy S24 with Android 14
4. You can see that initial `CardField` text color is white in preferred networks dropdown list

**Expected behavior**
The `CardField` has initially the proper text color, the default grey icon should show up, and the text color of the differents networks should not be white.

**Screenshots**

![Screenshot 2024-10-01 at 15 03 17](https://github.com/user-attachments/assets/cbda82d7-76b8-403e-a223-34b203cc6df7)
![Screenshot 2024-10-01 at 15 02 49](https://github.com/user-attachments/assets/ff48563e-60b6-4984-a6a7-5139f920e027)
<img width="550" alt="Screenshot 2024-10-01 at 15 27 30" src="https://github.com/user-attachments/assets/a5a63463-160b-4d6f-8e4d-6e7c8a5244af">

You can find 2 videos below, one from a Samsung Galaxy S24 on Android 14, and a video from an Android Emulator with Android 8.

https://github.com/user-attachments/assets/44b7d04e-6297-465a-9eb1-5637b26f0557
https://github.com/user-attachments/assets/619d0887-72d5-4631-944b-5f7a4d24b081

**Desktop (please complete the following information):**
 - OS: Android 14 

**Smartphone (please complete the following information):**
 - Device: Samsung S24, Android 8 emulator

**Additional context**

Stripe sdk ->  "@stripe/stripe-react-native": "0.38.6"

Here is the code of the `CardField` :

```javascript
<CardField
    style={styles.cardField}
    cardStyle={styles.cardStyle}
    onCardChange={setCardDetails}
    postalCodeEnabled={false}
    autofocus
    preferredNetworks={[
      CardBrand.Mastercard,
      CardBrand.Visa,
      CardBrand.CartesBancaires,
    ]}
/>
```
 
And here is the `styles` object used by the `CardField`:

```css
const styles = StyleSheet.create({
  container: {
    marginTop: 15,
    marginHorizontal: 15,
  },
  label: {
    color: theme.secondaryColor,
    fontSize: 16,
    fontWeight: '500',
  },
  cardField: {
    marginTop: 20,
    width: '100%',
    height: 50,
  },
  cardStyle: {
    textColor: '#5E5E5E',
    backgroundColor: '#FAFAFA',
    borderColor: '#9B9B9B',
    borderWidth: 1,
  },
  button: {
    marginTop: 20,
  },
});
```
